version: '3.9'

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always
    networks:
      seas_network:
        ipv4_address: 175.20.0.100
    ports:
      - '1884:1884'
      - '9002:9002'

  resources:
    image: magiteam/resources
    container_name: resources
    build:
      context: ./resources/
      dockerfile: Dockerfile
    restart: always
    networks:
      seas_network:
        ipv4_address: 175.20.0.101
    depends_on:
      - mqtt-broker

  mape-monitor:
    image: magiteam/mape-monitor
    container_name: mape-monitor
    build:
      context: ./mape-monitor/
      dockerfile: Dockerfile
    restart: always
    networks:
      seas_network:
        ipv4_address: 175.20.0.102
    depends_on:
      - mqtt-broker

  mape-knowledge:
    image: influxdb:latest
    container_name: mape-knowledge
    restart: always
    environment:
              - DOCKER_INFLUXDB_INIT_MODE=setup
              - DOCKER_INFLUXDB_INIT_USERNAME=admin
              - DOCKER_INFLUXDB_INIT_PASSWORD=adminse4as
              - DOCKER_INFLUXDB_INIT_ORG=univaq
              - DOCKER_INFLUXDB_INIT_BUCKET=artexhibition
              - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=4qYRM7usBFEuc3Gxd01lC6Gpiohdwv4DWZ39xjhERohSKddjcpVdlDCzP6aCu8oT
    networks:
       seas_network:
          ipv4_address: 175.20.0.103
    ports:
      - '8086:8086'
      
networks:
  seas_network:
    ipam:
      config:
        - subnet: '175.20.0.0/20'